name: streamer-app
regions: 
  - fra
services:
  - name: web
    docker: 
      image: python:3.9-slim
    env:
      - key: PORT
        value: 8000
    ports:
      - port: 8000
        http: true
    routes:
      - path: /
    build:
      buildpack: python
      command: |
        apt-get update && apt-get install -y ffmpeg libavcodec-extra
        pip install --no-cache-dir -r requirements.txt
    run: |
      gunicorn --workers=2 --threads=4 --bind=0.0.0.0:$PORT app:app
